.\" Manpage for internsctl
.TH man 1 "10 Jan 2024" "1.0.0" "internsctl manual"
.SH NAME
internsctl \- manage interns
.SH SYNOPSIS
.B internsctl
[\fIOPTION\fR]
.P
.B internsctl
[\fICOMMAND\fR]
.SH DESCRIPTION
.B internsctl
is a command-line tool for managing interns.
.P
It provides various options and commands to interact with intern-related tasks.
.SH OPTIONS
.TP
.BR --version
Display version information.
.SH COMMANDS
.TP
.BR <command>
Execute a specific command related to interns.
.SH AUTHOR
This manual page was written by Sahil Mahawer.
.SH SEE ALSO
.BR man (1)

